### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by a-thay** [errata-ai/vale-atom#1]
1. Create a nested UL list under a H1 heading.
2. Change the bulleted list into H2s.
3. Also, generally, save the .md file. Error is thrown during saves, too.

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [vale-server](https://github.com/errata-ai/vale-atom) package 1.4.0

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///C:/Users/Aaron.Thayer/AppData/Local/atom/app-1.40.1/resources/app.asar/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/packages/vale-server/lib/init.coffee:88:31)
    at Request.self.callback (/packages/atom-beautify/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at /packages/atom-beautify/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at /packages/atom-beautify/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
     -0:32.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:31.9.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:31.9.0 editor:newline (input.hidden-input)
     -0:30.6.0 core:move-down (input.hidden-input)
     -0:30.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:29.4.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:29.4.0 editor:newline (input.hidden-input)
     -0:28.5.0 core:move-down (input.hidden-input)
     -0:28.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:27.7.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:27.7.0 editor:newline (input.hidden-input)
 12x -0:26.3.0 core:move-up (input.hidden-input)
     -0:18.1.0 intentions:highlight (input.hidden-input)
     -0:17.8.0 core:save (input.hidden-input)
     -0:07.3.0 intentions:highlight (input.hidden-input)
     -0:07.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-assistant 0.2.3 
asciidoc-image-helper 1.0.1 
asciidoc-preview 2.13.1 
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-live-server 2.3.0 
atom-wrap-in-tag 0.6.0 
atomic-chrome 0.3.3 
autocomplete-asciidoc 0.1.2 
busy-signal 2.0.1 
color-picker 2.3.0 
highlight-line 0.12.0 
insert-timestamp 0.2.4 
intentions 1.1.5 
language-asciidoc 1.11.0 
language-latex 1.2.0 
language-restructuredtext 1.1.2 
language-sphinx 0.1.9 
language-vba 0.2.5 
latex 0.50.2 
linter 2.3.1 
linter-textlint 5.0.0 
linter-ui-default 1.8.0 
markdown-pdf 2.2.0 
markdown-preview-enhanced 0.16.3 
markdown-writer 2.11.9 
multi-wrap-guide 1.1.8 
open-terminal-here 2.3.2 
pandoc-convert 1.1.1 
sphinx-preview 0.1.5 
Sublime-Style-Column-Selection 1.7.5 
sync-settings 0.8.6 
teletype 0.13.4 
vale-server 1.4.0 
```

**Comment by jdkato** [comment]
Thanks for the detailed report.

I've been unsuccessful at reproducing this so far but, just so we're clear, it's the act of performing the above 3 steps that triggers the error (not simply the resulting file), correct?

**Comment by jdkato** [comment]
Do you still experience this with `v1.5.0`?

**Comment by a-thay** [comment]
Heya, sorry for the delayed response! No, I'm not experiencing the error since upgrading. Thank you!
