### ISSUE TITLE
Uncaught TypeError: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by brest-amzn** [errata-ai/vale-atom#3]
[Enter steps to reproduce:]

1. Upgraded to Vale 1.5.
2. Open atom.
3. Open markdown file.
2. Vale no longer works in atom using the same settings as 1.4

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [vale-server](https://github.com/errata-ai/vale-atom) package 1.5.0

### Stack Trace

Uncaught TypeError: The "path" argument must be of type string. Received type undefined

```
At internal/validators.js:105

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:105:11)
    at Object.join (path.js:372:7)
    at Request._callback (/packages/vale-server/lib/init.coffee:128:34)
    at Request.self.callback (/packages/vale-server/node_modules/request/request.js:185:22)
    at Request.emit (events.js:194:13)
    at /packages/vale-server/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:194:13)
    at /packages/vale-server/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:282:20)
    at IncomingMessage.emit (events.js:199:15)
    at endReadableNT (_stream_readable.js:1141:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

### Commands

```
     -0:26 intentions:highlight (input.hidden-input)
     -0:25.9.0 core:save (input.hidden-input)
     -0:19 intentions:highlight (input.hidden-input)
     -0:18.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.3.0 
atomic-vale 1.9.0 
busy-signal 2.0.1 
copy-find-results 0.2.0 
devmind-beautifier 1.3.0 
duplicate-removal 0.1.3 
emmet 2.4.3 
gfm-pdf 0.3.5 
intentions 1.1.5 
jsonlint 1.1.4 
line-ending-converter 1.3.2 
linter 2.3.1 
linter-just-say-no 0.7.5 
linter-markdown 5.2.10 
linter-proselint 3.3.0 
linter-spell 0.15.0 
linter-ui-default 1.8.1 
linter-write-good 0.9.3 
markdown-to-html 0.5.0 
mr-markdown-pdf 1.6.0 
pandoc-convert 1.1.1 
pandoc-pdf 0.1.0 
platformio-ide-terminal 2.10.0 
pp-markdown 0.0.2 
pretty-json 2.1.2 
split-diff 1.6.1 
status-stats-jbrains 0.6.0 
test undefined 
toggle-gutter 0.3.4 
vale-server 1.5.0 
```

**Comment by brest-amzn** [comment]
Solved the issue, as per the NOTE on this page:
https://errata-ai.github.io/vale-server/docs/sync

**Vale Server requires that all paths (on both macOS and Windows) use a forward slash (/).**

In v.1.4, the StylesPath worked with backslashes (\), in 1.5 they do not. 

**To fix**

I updated the custom styles path's I was using and replaced the backslashes with forward slashes

**Old**: StylesPath = C:\Users\[user]\Desktop\styles 
**New**: StylesPath = C:/Users/[user]/Desktop/styles
