### ISSUE TITLE
Failed to load the vale-server package

### ISSUE THREAD

**Issue by rolfedh** [errata-ai/vale-atom#8]
[Enter steps to reproduce:]

1. ...I installed the prerequisite Vale Server and linter (with Cow powers) package.
2.  I installed vale-server package and restarted Atom.
![image](https://user-images.githubusercontent.com/350907/162633364-583efc69-307e-422f-bc68-8605e7dd4e82.png)
This action produces the following error:
![image](https://user-images.githubusercontent.com/350907/162633476-b8ea18e2-965e-4b35-8254-4e6b3530c574.png)

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: linux 5.4.0-107-generic
**Thrown From**: [vale-server](https://github.com/errata-ai/vale-atom) package 1.8.0

### Stack Trace

Failed to load the vale-server package

```
At Unexpected token 'export'

/home/rolfedh/.var/app/io.atom.Atom/data/packages/vale-server/node_modules/url-join/lib/url-join.js:60
export default function urlJoin() {
^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (vm.js:84:7)
    at NativeCompileCache.runInThisContext (/app/share/atom/resources/app/static/<embedded>:11:148814)
    at Module.get_Module._compile (/app/share/atom/resources/app/static/<embedded>:11:149668)
    at Object.value [as .js] (/app/share/atom/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/app/share/atom/resources/app/static/<embedded>:11:149207)
    at /packages/vale-server/lib/init.coffee:4:11)
    at /packages/vale-server/lib/init.coffee:1:1)
    at /packages/vale-server/lib/init.coffee:1:1)
    at Module.get_Module._compile (/app/share/atom/resources/app/static/<embedded>:11:149891)
    at Object.value [as .coffee] (/app/share/atom/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/app/share/atom/resources/app/static/<embedded>:1:756277)
    at requireModule (/app/share/atom/resources/app/static/<embedded>:14:1195620)
    at Package.requireMainModule (/app/share/atom/resources/app/static/<embedded>:11:3400284)
    at /app/share/atom/resources/app/static/<embedded>:11:3386824
    at Package.measure (/app/share/atom/resources/app/static/<embedded>:11:3385624)
    at Package.load (/app/share/atom/resources/app/static/<embedded>:11:3386397)
    at PackageManager.loadAvailablePackage (/app/share/atom/resources/app/static/<embedded>:11:384186)
    at PackageManager.loadPackage (/app/share/atom/resources/app/static/<embedded>:11:382914)
    at PackageManager.activatePackage (/app/share/atom/resources/app/static/<embedded>:11:385486)
    at /app/share/atom/resources/app/static/<embedded>:11:915033
    at r (/app/share/atom/resources/app/static/<embedded>:11:909639)
    at n (/app/share/atom/resources/app/static/<embedded>:14:1194943)
    at /app/share/atom/resources/app/static/<embedded>:14:1195097
    at Socket.<anonymous> (/app/share/atom/resources/app/static/<embedded>:14:1193699)
    at Socket.emit (events.js:228:7)
    at Pipe.<anonymous> (net.js:664:12)
```

### Commands

```
```

### Non-Core Packages

```
vale-server 1.8.0 
```

**Comment by JoeAldinger** [comment]
I have the same issue. Any suggestions?

**Comment by rolfedh** [comment]
> I have the same issue. Any suggestions?

No, I haven't found a solution, yet. I'll post here and notify you if I do.

**Comment by jdkato** [comment]
Thanks for the report.

I'm going to be working on getting new releases out for all of the editor plugins to support the v2.16.0 features soon.

**Comment by jdkato** [comment]
This issue has been fixed, but the `apm publish` command is not working. 

I seem to be running into https://github.com/atom/apm/issues/572: the command fails with "Application error" and the latest version can't be installed from Atom ("Package version: 1.9.2 not found") although it shows up at https://atom.io/packages/vale-server.

**Comment by javimed** [comment]
Perhaps something to do with tags?

![imagen](https://user-images.githubusercontent.com/47069802/168626042-44948ac6-d4de-4e8d-b5e2-2b7edfda7eb6.png)
![imagen](https://user-images.githubusercontent.com/47069802/168626939-d8e7ef8c-49dd-49b6-a306-f0c2a72d824b.png)
https://github.com/errata-ai/vale-atom/releases/tag/v1.10.0
![imagen](https://user-images.githubusercontent.com/47069802/168626155-f88724c6-bb84-4d17-a5cc-cf9bebb77ce3.png)
![imagen](https://user-images.githubusercontent.com/47069802/168627445-66d7d95f-74fd-4563-ad6e-25b5122389c0.png)

![imagen](https://user-images.githubusercontent.com/47069802/168626443-5ba95473-80f2-4727-994a-fd66cc3f2ac8.png)

**Comment by jdkato** [comment]
Yes, as I said, the `apm` command is not working, which is why the tags are out of sync. You cannot add or remove versions -- the command always fails with `Application error`. I've done this over 14 times in the past, so I know how to release the package.

I'll try again when I have a chance, as I assume this will be fixed eventually.

**Comment by jdkato** [comment]
The "recently updated" section on `atom.io` also shows packages that were released years ago, so it's not even clear to me if *anyone* is able to publish.

**Comment by rolfedh** [comment]
Thanks, @jdkato. @javimed's suggestion and your responses have helped me better understand your previous mention of the APM issue. I've commented in that issue to help increase its visibility and priority.

**Comment by jdkato** [comment]
Just an update here: I tried again and the command is still failing with the same error.

**Comment by jdkato** [comment]
Thanks to this workaround (https://github.com/atom/apm/issues/572#issuecomment-1137204408), the new version should finally be installable.
